#!/usr/bin/env bash

fatal () {
    local MESSAGE="$1"
    local DELAY="30"

    echo "$MESSAGE"
    echo "The system will be rebooted in ${DELAY} seconds. Press enter to skip..."

    timeout --foreground "${DELAY}" bash -c "read" && sleep infinity

    reboot --force
    exit 1
}

if ! mkdir /efivars; then
    fatal "Make efivars directory failed!"
fi

if ! mount --types efivarfs efivars /efivars; then
    fatal "Mount efivarfs failed!"
fi

if ! bootstrap --efivars /efivars; then
    fatal "Bootstrap failed!"
fi

exec /usr/lib/systemd/systemd --unit=hello.service
